package geometry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/stillwater-sc/godfa/api/models"
)

/*GetConvexHullOK return the convex hull of a constraint set

swagger:response getConvexHullOK
*/
type GetConvexHullOK struct {

	/*
	  In: Body
	*/
	Payload *models.Convexhull `json:"body,omitempty"`
}

// NewGetConvexHullOK creates GetConvexHullOK with default headers values
func NewGetConvexHullOK() *GetConvexHullOK {
	return &GetConvexHullOK{}
}

// WithPayload adds the payload to the get convex hull o k response
func (o *GetConvexHullOK) WithPayload(payload *models.Convexhull) *GetConvexHullOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get convex hull o k response
func (o *GetConvexHullOK) SetPayload(payload *models.Convexhull) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConvexHullOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetConvexHullDefault error

swagger:response getConvexHullDefault
*/
type GetConvexHullDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConvexHullDefault creates GetConvexHullDefault with default headers values
func NewGetConvexHullDefault(code int) *GetConvexHullDefault {
	if code <= 0 {
		code = 500
	}

	return &GetConvexHullDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get convex hull default response
func (o *GetConvexHullDefault) WithStatusCode(code int) *GetConvexHullDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get convex hull default response
func (o *GetConvexHullDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get convex hull default response
func (o *GetConvexHullDefault) WithPayload(payload *models.Error) *GetConvexHullDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get convex hull default response
func (o *GetConvexHullDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConvexHullDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
