package geometry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/stillwater-sc/godfa/api/models"
)

// GetConvexHullHandlerFunc turns a function with the right signature into a get convex hull handler
type GetConvexHullHandlerFunc func(GetConvexHullParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConvexHullHandlerFunc) Handle(params GetConvexHullParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetConvexHullHandler interface for that can handle valid get convex hull params
type GetConvexHullHandler interface {
	Handle(GetConvexHullParams, *models.Principal) middleware.Responder
}

// NewGetConvexHull creates a new http.Handler for the get convex hull operation
func NewGetConvexHull(ctx *middleware.Context, handler GetConvexHullHandler) *GetConvexHull {
	return &GetConvexHull{Context: ctx, Handler: handler}
}

/*GetConvexHull swagger:route POST /convexhull geometry getConvexHull

Calculate the Convex Hull of a Domain

Given a domain defined by a constraint set, calculate the vertices and faces of the Convex Hull


*/
type GetConvexHull struct {
	Context *middleware.Context
	Handler GetConvexHullHandler
}

func (o *GetConvexHull) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetConvexHullParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
