package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "encoding/json"

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/dfa.api.v1+json"
  ],
  "produces": [
    "application/dfa.api.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Provides geometry, combinatorics, integer programming, functional simulation,\nand other domain flow algorithm analysis services\n",
    "title": "Stillwater Domain Flow Service API",
    "contact": {
      "name": "Stillwater Supercomputing, Inc. Domain Flow API team",
      "url": "http://www.stillwater-sc.com/about.html",
      "email": "dfa-services@stillwater-sc.com"
    },
    "license": {
      "name": "creative commons"
    },
    "version": "0.1.0"
  },
  "host": "localhost",
  "basePath": "/api/dfa",
  "paths": {
    "/": {
      "get": {
        "description": "Return the version of the DFA API\n",
        "tags": [
          "root"
        ],
        "summary": "API version",
        "operationId": "version",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/version"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/convexhull": {
      "post": {
        "description": "Given a domain defined by a constraint set, calculate the vertices and faces of the Convex Hull\n",
        "tags": [
          "geometry"
        ],
        "summary": "Calculate the Convex Hull of a Domain",
        "operationId": "getConvexHull",
        "parameters": [
          {
            "name": "domain",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/constraintSet"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "return the convex hull of a constraint set",
            "schema": {
              "$ref": "#/definitions/convexhull"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "constraint": {
      "type": "object",
      "properties": {
        "dimension": {
          "type": "integer",
          "enum": [
            1,
            2,
            3
          ]
        },
        "rhs": {
          "type": "number",
          "format": "float32"
        },
        "vector": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        }
      }
    },
    "constraintSet": {
      "type": "object",
      "properties": {
        "constraints": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/constraint"
          }
        }
      }
    },
    "convexhull": {
      "type": "object",
      "properties": {
        "vertices": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "string"
    },
    "value": {
      "type": "number",
      "format": "float32"
    },
    "version": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "securityHeader": {
      "type": "apiKey",
      "name": "X-Token",
      "in": "header"
    },
    "securityQuery": {
      "type": "apiKey",
      "name": "token",
      "in": "query"
    }
  },
  "security": [
    {
      "securityHeader": []
    },
    {
      "securityQuery": []
    }
  ]
}`))
}
