package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Convexhull convexhull
// swagger:model convexhull
type Convexhull struct {

	// vertices
	Vertices []Value `json:"vertices"`
}

// Validate validates this convexhull
func (m *Convexhull) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVertices(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Convexhull) validateVertices(formats strfmt.Registry) error {

	if swag.IsZero(m.Vertices) { // not required
		return nil
	}

	for i := 0; i < len(m.Vertices); i++ {

		if err := m.Vertices[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vertices" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}
