package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Value value
// swagger:model value
type Value float64

// Validate validates this value
func (m Value) Validate(formats strfmt.Registry) error {
	return nil
}
