package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Version version
// swagger:model version
type Version string

// Validate validates this version
func (m Version) Validate(formats strfmt.Registry) error {
	return nil
}
